name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
          - 'src/frontend/**'
          - '**/*.md'
          - '**/cicd-google-cloudrun.yml'
jobs:
  run_fti_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      # Run the shell script
      - name: Execute pipeline
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          chmod +x run_pipeline.sh
          source ./run_pipeline.sh
