name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
          - 'src/frontend/**'
          - '**/*.md'
          - '**/cicd-google-cloudrun.yml'
jobs:
  run_fti_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: cache virtualenv
        uses: actions/cache@v3
        id: cache-venv
        with:
          path: ./.venv/
          key: ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-

      - name: Install dependencies
        shell: bash
        if: steps.cache_env.outputs.cache-hit != 'true'
        run: |
          python -m venv ./.venv
          source ./.venv/bin/activate
          python -m pip install -r requirements.txt

      # Run the shell script
      - name: Execute pipeline
        run: |
          source ./.venv/bin/activate
          echo "${{ secrets.ENV_FILE }}" > .env
          chmod +x run_pipeline.sh
          ./run_pipeline.sh