name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
          - 'src/frontend/**'
          - '**/*.md'
          - 'media/**'
          - '**/cicd-google-cloudrun.yml'
jobs:
  run_fti_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install Venv
        run: uv venv
      - name: Install Dependencies
        run: uv sync
      # Run the shell script
      - name: Execute pipeline
        run: |
          source .venv/bin/activate  # Activate virtual environment
          export PYTHONPATH=$(pwd)/$PYTHONPATH
          echo "${{ secrets.ENV_FILE }}" > .env
          source .env
          source ./run_pipeline.sh
